## Les Routes sont en annotation directement dans les Controllers. ##
## Seules les routes des temlates sont présentes ici ##

app:
    resource: "@CEOFESABundle/Controller"
    type: annotation
    prefix: /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"