parameters:
    tarif_ofesa: 12.00
    tarif_straitant: 13
    max_heures: 399
    contact_mail1: 'webmestre@chantierecole.org'
    contact_mail2: 'developpeur@chantierecole.org'
    contact_mail3: 'a.clavier@ofesa.org'