services:
    ceofesa.registration.form.type:
        class: CEOFESABundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: ceofesa_registration }

    ceofesa.form.type.duration:
        class: CEOFESABundle\Form\Type\DurationType
        tags:
            - { name: form.type, alias: duration }

    ceofesa.form.type.dashboard:
        class: CEOFESABundle\Form\Type\DashboardType
        arguments:
            - "@security.authorization_checker"
        tags:
            - { name: form.type, alias: dashboard_type }

    validator.unique.parcours:
        class: CEOFESABundle\Validator\Constraints\ParcoursValidator
        arguments: ["%max_heures%","@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: max_heures_parcours }

    validator.unique.dparcours:
        class: CEOFESABundle\Validator\Constraints\DParcoursValidator
        arguments: ["%max_heures%","@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: max_heures_dparcours }

    ceofesa.validator.class_session:
        class: CEOFESABundle\Validator\Constraints\SessionValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: ceofesa.validator.class_session }

    ceofesa.validator.class_presence:
       class: CEOFESABundle\Validator\Constraints\PresenceValidator
       tags:
           - { name: validator.constraint_validator, alias: ceofesa.validator.class_presence }

    kernel.listener.login_listener:
        class: CEOFESABundle\EventListener\LoginListener
        arguments: ['@security.context', '@session']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }

    twig.extension.duration:
        class: CEOFESABundle\Twig\DurationTwigExtension
        tags:
            - { name: twig.extension }

    ceofesa.dashboard.exporter:
        class: CEOFESABundle\Export\DashboardExporter
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@twig"
            - "@knp_snappy.pdf"
