services:
    ceofesa.registration.form.type:
        class: CEOFESABundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: ceofesa_registration }

    validator.unique.parcours:
        class: CEOFESABundle\Validator\Constraints\ParcoursValidator
        arguments: ["%max_heures%"]
        tags:
            - { name: validator.constraint_validator, alias: max_heures }

    kernel.listener.login_listener:
        class: CEOFESABundle\EventListener\LoginListener
        arguments: ['@security.context', '@session']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }