services:
    ceofesa.registration.form.type:
        class: CEOFESABundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: ceofesa_registration }

    validator.unique.parcours:
        class: CEOFESABundle\Validator\Constraints\ParcoursValidator
        arguments: ["%max_heures%","@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: max_heures_parcours }

    validator.unique.dparcours:
        class: CEOFESABundle\Validator\Constraints\DParcoursValidator
        arguments: ["%max_heures%","@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: max_heures_dparcours }

    ceofesa.validator.class_session:
        class: CEOFESABundle\Validator\Constraints\SessionValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: ceofesa.validator.class_session }

    kernel.listener.login_listener:
        class: CEOFESABundle\EventListener\LoginListener
        arguments: ['@security.context', '@session']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }
